### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [9]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [10]:
url1 = ("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")

cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")

url2 =("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [ ]:
# columnas vacias

cars1.isna().all() # comprobacion columnas vacias

cars1.dropna(axis=1) 
cars1

# otra forma
# cars1 = cars1.loc[:, "mpg":"car"]  -->  cars1.isna().all() # comprobacion columnas vacias


# para hacer el resto de ejercicios
# copia ---> cars_1 = cars1.copy()
# cars1.dropna(axis=1, inplace=True) 
# inplace=True para hacer el resto de ejercicios y tener un DataFrame sin NaN

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick,NaN,NaN,NaN,NaN,NaN
194,22.5,6,232,90,3085,17.6,76,1,amc hornet,NaN,NaN,NaN,NaN,NaN
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette,NaN,NaN,NaN,NaN,NaN
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody,NaN,NaN,NaN,NaN,NaN
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in each dataset?

In [ ]:
cars1.shape
print(cars1.shape)
cars2.shape
cars1.shape
print(cars2.shape)


# filas, columnas

(198, 14)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [ ]:
# unir cars1 y cars2
# concat -o- merge --> columna comun
cars = pd.merge(cars1,cars2, how= "outer")  # outer --> todas las de las dos tablas
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d,NaN,NaN,NaN,NaN,NaN
1,10.0,8,307,200,4376,15.0,70,1,chevy c20,NaN,NaN,NaN,NaN,NaN
2,10.0,8,360,215,4615,14.0,70,1,ford f250,NaN,NaN,NaN,NaN,NaN
3,11.0,8,318,210,4382,13.5,70,1,dodge d200,NaN,NaN,NaN,NaN,NaN
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel),NaN,NaN,NaN,NaN,NaN
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel),NaN,NaN,NaN,NaN,NaN
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl,NaN,NaN,NaN,NaN,NaN
397,46.6,4,86,65,2110,17.9,80,3,mazda glc,NaN,NaN,NaN,NaN,NaN

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [ ]:
owner = np.random.randint(15000, 73000, size = cars.shape[0])
owner                        

cars["owner"] = owner
cars 


# crear una nueva columna para el DataFrame llamada "owner" 
# con numeros aleatorios de 15.000 a 73.000 (np.random.randint())


# crear una serie
# owner = pd.Series(np.random.randint(15000, 73000, size=cars.shape[0]))

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owner
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d,NaN,NaN,NaN,NaN,NaN,36346
1,10.0,8,307,200,4376,15.0,70,1,chevy c20,NaN,NaN,NaN,NaN,NaN,72196
2,10.0,8,360,215,4615,14.0,70,1,ford f250,NaN,NaN,NaN,NaN,NaN,57150
3,11.0,8,318,210,4382,13.5,70,1,dodge d200,NaN,NaN,NaN,NaN,NaN,51424
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega,NaN,NaN,NaN,NaN,NaN,35157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel),NaN,NaN,NaN,NaN,NaN,56008
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,44407
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel),NaN,NaN,NaN,NaN,NaN,40428
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl,NaN,NaN,NaN,NaN,NaN,44869
397,46.6,4,86,65,2110,17.9,80,3,mazda glc,NaN,NaN,NaN,NaN,NaN,24518

### Step 8. Add the column owners to cars

In [22]:
cars["owner"] = "owner"
cars

# añadir columna "owner"

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owner
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d,NaN,NaN,NaN,NaN,NaN,owner
1,10.0,8,307,200,4376,15.0,70,1,chevy c20,NaN,NaN,NaN,NaN,NaN,owner
2,10.0,8,360,215,4615,14.0,70,1,ford f250,NaN,NaN,NaN,NaN,NaN,owner
3,11.0,8,318,210,4382,13.5,70,1,dodge d200,NaN,NaN,NaN,NaN,NaN,owner
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega,NaN,NaN,NaN,NaN,NaN,owner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel),NaN,NaN,NaN,NaN,NaN,owner
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,owner
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel),NaN,NaN,NaN,NaN,NaN,owner
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl,NaN,NaN,NaN,NaN,NaN,owner
397,46.6,4,86,65,2110,17.9,80,3,mazda glc,NaN,NaN,NaN,NaN,NaN,owner