# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [59]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [ ]:
# url = https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv


df = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv")
df



# en la correccion de clase
# idea para visualizar las columnas de la tabla al completo

# pd.set_option("display.max_rows", 500) filas
# pd.set_option("display.max_columns", 500) columnas
# # pd.set_option("display.max_width", 1000) cncho de todo el dataframe

# df.columns (sale el nombre de todas las columnas)
# "guardian" in df.columns   (True)

# df.duplicated().any()   --> saber si hay filas duplicadas   False o True
# df.columns.duplicated().any()  --> saber si hay columnas duplicadas  False o True

# df.isna() --> donde estan los valores nulos missing NaN

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
# df.T  la traspuesta, cambiar filas por columnas, no lo modifica, 
# da uno nuevo traspuesto si se quiere modificar se sobr-escribe le asigna una variable

# df[df.index.duplicated()] --> donde esta duplicado el indice
# df[~df.index.duplicated()] --> ~ donde NO  esta duplicado el indice es lo que muestra

# filas enteras que sean iguales

# df.index.duplicated(keep="first") --> 
# keep first la primera vez que aparece un duplicado no lo es
# keep= false si parece dos veces quita las dos, que no aparezca ningun duplicado

# df.drop_duplicates(keep) --> drop duplicado
# diferencia entre duplicated (devuelve una serie de booleanos con los que estanduplicados)
# es decir que está duplicado

# y drop duplicates (devuelve) borra los duplicados
# si solo quiero extraer los duplicados con una mascara pregunto si esta duplicado

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [ ]:
df4 = df.loc[:, 'school':'guardian']
#df4.head()  
df4

# head() por defecto las 5 primeras
# comprobar con mas facilidad
# ver los nombres de las columnas y revisar el tipo de contenido

# head <--> tail

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [ ]:
# en la correccion en clase

# lambda palabra reservada de python para hacer funciones
# lambda x,y: x + y
# tenemos x e y y devuelve x + y
# lambda x,y: x + y if x > 10 else None


# lambda x,y: x + y if x > 10 else 20
# se la puede nombrar si despues se la quiere utilizar
# otra_funcion = lambda x,y: x + y if x > 10 else 20
# otra_funcion (2,5) --> devuelvve 20

# funcion anonima la utilzamos por ejempolo cuando queremos hacer...
# en una columna a cada valor le queremos sumar dos df.age +2 lo suma
# si queremos a la columna sumarle dos si el sexo es F y sino le resto 200
# lo hacemos con una funcion
# 

def resta_cosas(x):
    if x ["sex"] == "F":
        return x["age"] + 2
    elif x["sex"] == "M":
        return x["age"] - 200

df.apply(resta_cosas, axis = 1) # --> columnas
# este apply accede columna sex  devuelve una serie

# x es el dataframe completo y aqui trabaja por columnas

# al reves axis = 0 para que funcione una opcion es dt.T trasponerlo y ya podemos
# trabajar con esos datos en axis = 1 por columnas de nuevo para que funcione y tambien apply


# lambda, funcion anonima, no tiene nombre, se puede renombar y utilizar despues

# df.apply(lambda x: x["age"] + 20000 if x["sex"] == "F" else x["age"] - 200, axis =1)

# otra funcion lambda

# list(map(lambda x : str.upper(x), ["hola", "adios"]))  --> map

In [62]:

letra_capital = lambda x: x.capitalize()     
df5 = letra_capital
df5("madrid")


# .str.capitalize(): Pone la primera letra en mayúscula, letra capital
# y convierte el resto de los caracteres a minúsculas.

# .str.title(): Pone en mayúscula la primera letra de cada palabra en el texto

'Madrid'

### Step 6. Capitalize both Mjob and Fjob

In [ ]:
df[['Mjob', 'Fjob']].apply(lambda x: x.apply(df5))


# en la correccion de clase 21/10/2026
# df[['Mjob', 'Fjob']].apply(lambda x: x.str.capitalize()) #, axis = 0) = al de defecto
# por defecto se trabaja-barre recorriendo filas trabaja en la columna

# apply necesita una funcion que se le quiere aplicar, lambda es una funcion

         Mjob      Fjob
0     At_home   Teacher
1     At_home     Other
2     At_home     Other
3      Health  Services
4       Other     Other
..        ...       ...
390  Services  Services
391  Services  Services
392     Other     Other
393  Services     Other
394     Other   At_home

[395 rows x 2 columns]

### Step 7. Print the last elements of the data set.

In [64]:
#1
df[-5:]

#2
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [ ]:
df["Mjob"] = df["Mjob"].apply(df5)   # letra_capital
df["Fjob"] = df["Fjob"].apply(df5)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,40,30,40,10,10,30,60,50,60,60
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,50,30,30,10,10,30,40,50,50,60
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,40,30,20,20,30,30,100,70,80,100
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,30,20,20,10,10,50,20,150,140,150
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,40,30,20,10,20,50,40,60,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,...,50,50,40,40,50,40,110,90,90,90
391,MS,M,170,U,LE3,T,30,10,Services,Services,...,20,40,50,30,40,20,30,140,160,160
392,MS,M,210,R,GT3,T,10,10,Other,Other,...,50,50,30,30,30,30,30,100,80,70
393,MS,M,180,R,LE3,T,30,20,Services,Other,...,40,40,10,30,40,50,0,110,120,100
394,MS,M,190,U,LE3,T,10,10,Other,At_home,...,30,20,30,30,30,50,50,80,90,90

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [ ]:
# funcion def majority

def majority(x):
    return x > 17

df["legal_drinker"] = df["age"].apply(majority)

df


# en correccion de clase
# majority = lambda age_colum: (age_colum > 17)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,4,4,5,4,11,9,9,9,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,4,5,3,4,2,3,14,16,16,False
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,3,3,3,3,3,10,8,7,True
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,1,3,4,5,0,11,12,10,True
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,2,3,3,3,5,5,8,9,9,True

In [ ]:
df[["age", "legal_drinker"]]
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father,False

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [ ]:
df[df.select_dtypes("number").columns] * 10   
df

# df[:]*10  # multiplica todas las columnas por 10 no solo los numeros
# select_dtypes("number").columns

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,180,U,GT3,A,40,40,at_home,teacher,...,40,30,40,10,10,30,60,50,60,60
1,GP,F,170,U,GT3,T,10,10,at_home,other,...,50,30,30,10,10,30,40,50,50,60
2,GP,F,150,U,LE3,T,10,10,at_home,other,...,40,30,20,20,30,30,100,70,80,100
3,GP,F,150,U,GT3,T,40,20,health,services,...,30,20,20,10,10,50,20,150,140,150
4,GP,F,160,U,GT3,T,30,30,other,other,...,40,30,20,10,20,50,40,60,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,services,services,...,50,50,40,40,50,40,110,90,90,90
391,MS,M,170,U,LE3,T,30,10,services,services,...,20,40,50,30,40,20,30,140,160,160
392,MS,M,210,R,GT3,T,10,10,other,other,...,50,50,30,30,30,30,30,100,80,70
393,MS,M,180,R,LE3,T,30,20,services,other,...,40,40,10,30,40,50,0,110,120,100
394,MS,M,190,U,LE3,T,10,10,other,at_home,...,30,20,30,30,30,50,50,80,90,90

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,mother,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,course,father,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,other,mother,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,home,mother,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,course,other,True
391,MS,M,170,U,LE3,T,30,10,Services,Services,course,mother,False
392,MS,M,210,R,GT3,T,10,10,Other,Other,course,other,True
393,MS,M,180,R,LE3,T,30,20,Services,Other,course,mother,True
394,MS,M,190,U,LE3,T,10,10,Other,At_home,course,father,True

school           object
sex              object
age               int64
address          object
famsize          object
Pstatus          object
Medu              int64
Fedu              int64
Mjob             object
Fjob             object
reason           object
guardian         object
legal_drinker      bool
dtype: object