# Occupation

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
url = ("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")

users = pd.read_csv(url, sep="|")#, index_col ="user_id")

users = pd.read_csv(url, sep="|", index_col ="user_id")
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. Discover what is the mean age per occupation

In [4]:

users.groupby("occupation")["age"].mean()

# mean 

# en correccion de clase si se quiere ver un dataframegroupby o seriebroupby se pasa a LISTA
# porque sino para poder mostrarlo hay que llegar hasta el final, en este caso la media mean()
# users.groupby("occupation")["age"].mean()
# list(users.groupby("occupation")["age"].mean())

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [5]:
# 5 -- >  users
# hombres de mayor a menor

# gender_n

In [ ]:
# en la correccion de clase 21/10/2026

ds = users.copy()
ds = ds.groupby("gender").count()
ds

# contar cuantos hombres hay y cuantas mujeres hay

        age  occupation  zip_code
gender
F       273         273       273
M       670         670       670

In [12]:
# continuacion

def gender_to_numeric(x):
    if x == "M":
        return 1
    if x == "F":
        return 0

users["gender_n"] = users["gender"].apply(gender_to_numeric)
users

         age gender     occupation zip_code  gender_n
user_id
1         24      M     technician    85711         1
2         53      F          other    94043         0
3         23      M         writer    32067         1
4         24      M     technician    43537         1
5         33      F          other    15213         0
...      ...    ...            ...      ...       ...
939       26      F        student    33319         0
940       32      M  administrator    02215         1
941       20      M        student    97229         1
942       48      F      librarian    78209         0
943       22      M        student    77841         1

[943 rows x 5 columns]

In [ ]:
# continuacion

users.groupby("occupation").gender_n.sum()

# hace la suma agrupando teniendo en cuenta que siendo hombre vale 1 y  mujer 0
# suma los 1 los hombres porque el 0 no tiene valor no suma 
# y se sabe cual de cada ocupacion es hombre

occupation
administrator     43
artist            15
doctor             7
educator          69
engineer          65
entertainment     16
executive         29
healthcare         5
homemaker          1
lawyer            10
librarian         22
marketing         16
none               5
other             69
programmer        60
retired           13
salesman           9
scientist         28
student          136
technician        26
writer            26
Name: gender_n, dtype: int64

In [ ]:
users.occupation.value_counts()  
#

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [16]:
a = (users.groupby("occupation").gender_n.sum() / users.occupation.value_counts() )
     # dividido entre 
a

occupation
administrator    0.544304
artist           0.535714
doctor           1.000000
educator         0.726316
engineer         0.970149
entertainment    0.888889
executive        0.906250
healthcare       0.312500
homemaker        0.142857
lawyer           0.833333
librarian        0.431373
marketing        0.615385
none             0.555556
other            0.657143
programmer       0.909091
retired          0.928571
salesman         0.750000
scientist        0.903226
student          0.693878
technician       0.962963
writer           0.577778
dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [7]:

users.groupby("occupation")["age"].agg(["min", "max"])   # agg

# en la guia -->
# agg: admite varios métodos de agregación, incluidas funciones definidas
# y funciones definidas como 'sum', 'mean'...

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [8]:
users.groupby(["occupation", "gender"])["age"].mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [ ]:
# 8 --> pistas en la correccion de clase 21/10/2026 para que lo sigamos intentando

# pivot table